# Generated by Django 3.2.4 on 2021-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/logos/'),
        ),
    ]
