# Generated by Django 3.2.4 on 2021-07-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_worksamples_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choosetemplate',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.choosetemplate'),
        ),
    ]
