# Generated by Django 3.2.4 on 2021-07-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210701_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
    ]
